import Head from 'next/head';
import Image from 'next/image';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        {' '}
        <main className='flex justify-center'>
          <div className='flex flex-col items-center justify-center w-[600px] shadow-2xl m-10 p-4'>
            <Image
              src='https://res.cloudinary.com/doalzf6o2/image/upload/v1678421121/logo_hozn4t.png'
              height={100}
              width={100}
              alt='logo'
            />
            <p className='text-center text-3xl p-6'>
              America&apos;s #12{' '}
              <span className='font-extrabold'>Meal Delivery Service</span>
            </p>
            <div className='p-6'>
              <label
                htmlFor='street-address'
                className='block text-sm font-medium leading-6 text-gray-900'
              >
                Check if delivery service is available at your location
              </label>
              <div className='flex flex-row gap-4 items-center'>
                <input
                  type='text'
                  name='street-address'
                  id='street-address'
                  autoComplete='street-address'
                  className='w-[400px] mt-2 block rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6'
                />
                <button className='px-8 bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 rounded-full'>
                  Search
                </button>
              </div>
              <div className='flex justify-center gap-6 mt-4'>
                <div className='mb-[0.125rem] block min-h-[1.5rem] pl-[1.5rem]'>
                  <input
                    type='radio'
                    name='available'
                    value='available'
                    id='radioDefault01'
                  />
                  <label
                    className='mt-px inline-block pl-[0.15rem] hover:cursor-pointer'
                    htmlFor='radioDefault01'
                  >
                    Available
                  </label>
                </div>
                <div className='mb-[0.125rem] block min-h-[1.5rem] pl-[1.5rem]'>
                  <input
                    type='radio'
                    name='unavailable'
                    value='unavailable'
                    id='radioDefault02'
                  />
                  <label
                    className='mt-px inline-block pl-[0.15rem] hover:cursor-pointer'
                    htmlFor='radioDefault02'
                  >
                    Unavailable
                  </label>
                </div>
              </div>
            </div>
          </div>
        </main>
      </main>
    </>
  );
}
